export function $S(transformer: Function, ...bindings: Function[]): () => any;
export function $R(transformer: Function, ...bindings: Function[]): () => any;
export function $NOT(signal: any): () => any;
export function $IS(signal: any): () => any;
export function $EQStrict(to: any, signal: any): () => any;
export function $NEQStrict(to: any, signal: any): () => any;
export function $EQ(to: any, signal: any): () => any;
export function $NEQ(to: any, signal: any): () => any;
export function $If(signal: any, t: any, f: any): () => any;
export function $Map(map: any, signal: any): () => any;
//# sourceMappingURL=combineState.d.ts.map