// import { GlobalRegistrator } from '@happy-dom/global-registrator'

import { GlobalWindow, Window } from 'happy-dom'

const IGNORE_LIST = [
  'undefined',
  'NaN',
  'global',
  'globalThis',

  // 'console',
  'performance',
  'Infinity',
  // 'self',

  // 'Infinity',
  // 'v8debug',
  // 'gc',

  // 'Bun',
  // 'Node',
  // 'Attr',
  // 'SVGSVGElement',
  // 'SVGElement',
  // 'SVGGraphicsElement',
  // 'Text',
  // 'Comment',
  // 'ShadowRoot',
  // 'ProcessingInstruction',
  // 'Element',
  // 'CharacterData',
  // 'DocumentType',
  // 'HTMLAnchorElement',
  // 'HTMLButtonElement',
  // 'HTMLOptGroupElement',
  // 'HTMLOptionElement',
  // 'HTMLElement',
  // 'HTMLUnknownElement',
  // 'HTMLTemplateElement',
  // 'HTMLFormElement',
  // 'HTMLInputElement',
  // 'HTMLSelectElement',
  // 'HTMLTextAreaElement',
  // 'HTMLImageElement',
  // 'HTMLStyleElement',
  // 'HTMLLabelElement',
  // 'HTMLSlotElement',
  // 'HTMLMetaElement',
  // 'HTMLMediaElement',
  // 'HTMLAudioElement',
  // 'HTMLVideoElement',
  // 'HTMLBaseElement',
  // 'HTMLDialogElement',
  // 'HTMLHeadElement',
  // 'HTMLTitleElement',
  // 'HTMLBodyElement',
  // 'HTMLHeadingElement',
  // 'HTMLParagraphElement',
  // 'HTMLHRElement',
  // 'HTMLPreElement',
  // 'HTMLUListElement',
  // 'HTMLOListElement',
  // 'HTMLLIElement',
  // 'HTMLMenuElement',
  // 'HTMLDListElement',
  // 'HTMLDivElement',
  // 'HTMLAreaElement',
  // 'HTMLBRElement',
  // 'HTMLCanvasElement',
  // 'HTMLDataElement',
  // 'HTMLDataListElement',
  // 'HTMLDetailsElement',
  // 'HTMLDirectoryElement',
  // 'HTMLFieldSetElement',
  // 'HTMLFontElement',
  // 'HTMLHtmlElement',
  // 'HTMLLegendElement',
  // 'HTMLMapElement',
  // 'HTMLMarqueeElement',
  // 'HTMLMeterElement',
  // 'HTMLModElement',
  // 'HTMLOutputElement',
  // 'HTMLPictureElement',
  // 'HTMLProgressElement',
  // 'HTMLQuoteElement',
  // 'HTMLSourceElement',
  // 'HTMLSpanElement',
  // 'HTMLTableCaptionElement',
  // 'HTMLTableCellElement',
  // 'HTMLTableColElement',
  // 'HTMLTableElement',
  // 'HTMLTimeElement',
  // 'HTMLTableRowElement',
  // 'HTMLTableSectionElement',
  // 'HTMLFrameElement',
  // 'HTMLFrameSetElement',
  // 'HTMLEmbedElement',
  // 'HTMLObjectElement',
  // 'HTMLParamElement',
  // 'HTMLTrackElement',

  // 'Event',
  // 'UIEvent',
  // 'CustomEvent',
  // 'AnimationEvent',
  // 'KeyboardEvent',
  // 'MessageEvent',
  // 'MouseEvent',
  // 'PointerEvent',
  // 'FocusEvent',
  // 'WheelEvent',
  // 'InputEvent',
  // 'ErrorEvent',
  // 'StorageEvent',
  // 'SubmitEvent',
  // 'ProgressEvent',
  // 'MediaQueryListEvent',
  // 'ClipboardEvent',
  // 'AudioProcessingEvent',
  // 'BeforeInputEvent',
  // 'BeforeUnloadEvent',
  // 'BlobEvent',
  // 'CloseEvent',
  // 'CompositionEvent',
  // 'CSSFontFaceLoadEvent',
  // 'DeviceLightEvent',

  // 'DeviceMotionEvent',
  // 'DeviceOrientationEvent',
  // 'DeviceProximityEvent',
  // 'DOMTransactionEvent',
  // 'DragEvent',
  // 'EditingBeforeInputEvent',
  // 'FetchEvent',
  // 'GamepadEvent',
  // 'HashChangeEvent',
  // 'IDBVersionChangeEvent',
  // 'MediaStreamEvent',
  // 'MutationEvent',
  // 'OfflineAudioCompletionEvent',
  // 'OverconstrainedError',
  // 'PageTransitionEvent',
  // 'PaymentRequestUpdateEvent',
  // 'PopStateEvent',
  // 'RelatedEvent',
  // 'RTCDataChannelEvent',
  // 'RTCIdentityErrorEvent',
  // 'RTCIdentityEvent',
  // 'RTCPeerConnectionIceEvent',
  // 'SensorEvent',
  // 'SVGEvent',
  // 'SVGZoomEvent',
  // 'TimeEvent',
  // 'TouchEvent',
  // 'TrackEvent',
  // 'TransitionEvent',
  // 'UserProximityEvent',
  // 'WebGLContextEvent',
  // 'TextEvent',
  // 'NamedNodeMap',
  // 'NodeFilter',
  // 'NodeIterator',
  // 'TreeWalker',
  // 'MutationObserver',
  // 'MutationRecord',
  // 'CSSStyleDeclaration',
  // 'EventTarget',
  // 'MessagePort',
  // 'DataTransfer',
  // 'DataTransferItem',
  // 'DataTransferItemList',
  // 'URL',
  // 'Location',
  // 'CustomElementRegistry',
  // 'Window',
  // 'XMLSerializer',
  // 'ResizeObserver',
  // 'CSSStyleSheet',
  // 'Blob',
  // 'File',
  // 'DOMException',
  // 'History',
  // 'Screen',
  // 'Storage',
  // 'URLSearchParams',
  // 'HTMLCollection',
  // 'HTMLFormControlsCollection',
  // 'NodeList',
  // 'CSSUnitValue',
  // 'CSSRule',
  // 'CSSContainerRule',
  // 'CSSFontFaceRule',
  // 'CSSKeyframeRule',
  // 'CSSKeyframesRule',
  // 'CSSMediaRule',
  // 'CSSStyleRule',
  // 'CSSSupportsRule',
  // 'Selection',
  // 'Navigator',
  // 'MimeType',
  // 'MimeTypeArray',
  // 'Plugin',
  // 'PluginArray',
  // 'FileList',
  // 'DOMRect',
  // 'RadioNodeList',
  // 'ValidityState',
  // 'Headers',
  // 'XMLHttpRequestUpload',
  // 'XMLHttpRequestEventTarget',
  // 'ReadableStream',
  // 'WritableStream',
  // 'TransformStream',
  // 'AbortController',
  // 'AbortSignal',
  // 'FormData',
  // 'Permissions',
  // 'PermissionStatus',
  // 'Clipboard',
  // 'ClipboardItem',
  // 'onload',
  // 'onerror',

  // 'top',
  // 'parent',
  // 'window',
  // 'globalThis',

  // 'screenLeft',
  // 'screenTop',
  // 'screenX',
  // 'screenY',
  // 'crypto',
  // 'closed',
  // 'name',
  // 'Buffer',
  // 'customElements',
  // 'navigator',
  // 'history',
  // 'screen',
  // 'sessionStorage',
  // 'localStorage',
  // 'location',
  // 'console',
  // 'getComputedStyle',
  // 'getSelection',
  // 'scroll',
  // 'scrollTo',
  // 'blur',
  // 'focus',
  // 'open',

  // 'close',
  // 'matchMedia',
  // 'setTimeout',
  // 'clearTimeout',
  // 'setInterval',
  // 'clearInterval',
  // 'requestAnimationFrame',
  // 'cancelAnimationFrame',
  // 'queueMicrotask',
  // 'fetch',
  // 'btoa',
  // 'atob',
  // 'postMessage',
  // 'resizeTo',
  // 'resizeBy',
  // 'addEventListener',
  // 'removeEventListener',
  // 'dispatchEvent',
  // 'attachEvent',
  // 'detachEvent',
  // 'Response',
  // 'Request',
  // 'Image',
  // 'DocumentFragment',
  // 'FileReader',
  // 'DOMParser',
  // 'XMLHttpRequest',
  // 'Range',
  // 'Audio',
  // 'HTMLScriptElement',
  // 'HTMLLinkElement',
  // 'HTMLIFrameElement',
  // 'Document',
  // 'HTMLDocument',
  // 'XMLDocument',
  // 'SVGDocument',
  // 'document',
  // 'happyDOM',
  // 'Array',
  // 'ArrayBuffer',

  // 'Boolean',
  // 'DataView',
  // 'Date',
  // 'Error',

  // 'EvalError',
  // 'Float32Array',
  // 'Float64Array',
  // 'Function',
  // 'Int16Array',
  // 'Int32Array',
  // 'Int8Array',
  // 'Intl',
  // 'JSON',
  // 'Map',
  // 'Math',
  // 'NaN',
  // 'Number',
  // 'Object',
  // 'Promise',
  // 'RangeError',
  // 'ReferenceError',
  // 'RegExp',
  // 'Set',

  // 'String',
  // 'Symbol',
  // 'SyntaxError',
  // 'TypeError',
  // 'URIError',
  // 'Uint16Array',
  // 'Uint32Array',
  // 'Uint8Array',
  // 'Uint8ClampedArray',
  // 'WeakMap',
  // 'WeakSet',
  // 'decodeURI',
  // 'decodeURIComponent',
  // 'encodeURI',
  // 'encodeURIComponent',
  // 'eval',
  // 'escape',
  // 'global',
  // 'isFinite',
  // 'isNaN',
  // 'parseFloat',
  // 'parseInt',
  // 'undefined',
  // 'unescape',
  // 'gc',
  // 'v8debug',
]

const win = new GlobalWindow({})

globalThis.window = win
globalThis.document = win.document
globalThis.customElements = win.customElements
globalThis.HTMLElement = win.HTMLElement
for (var p in win) {
  if (IGNORE_LIST.includes(p)) continue
  // try {
  console.log('p', p)
  globalThis[p] = win[p]
  // } catch (e) {
  //   console.log(p, e.message, e)
  //   throw e
  // }
}

try {
  // GlobalRegistrator.register()
} catch (e) {
  console.log('GlobalRegistrator.register', e)
}
console.log('BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB')
